//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookshopWeb.Models
{
    using System;
    using System.Collections.Generic;
    using BookshopWeb.Models;

    public  class Cart
    {
       
        private BookDetail Book = new BookDetail();
        private int quantity;
       public BookDetail book { get { return Book; } set { Book = value; } }
        public Cart() { }
        public Cart(BookDetail Book,int quantity) {
            this.Book = Book;
            this.quantity = quantity;
        }
       
        public int CartID { get; set; }
        public Nullable<int> BookID { get; set; }
        public Nullable<int> Quantity { get; set; }
        public Nullable<int> TotalPrice { get; set; }
        public Nullable<int> UserID { get; set; }
    
        public virtual UserDetail UserDetail { get; set; }
       

       
    }
}
